# Generated by Django 2.1.5 on 2019-01-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Questions_Exam',
        ),
    ]
